import mongoose from 'mongoose';
await mongoose.connect(process.env.MONGODB_URI);
const db = mongoose.connection.db;
const c = db.collection('customers');
console.log('customers docs:', await c.countDocuments());
const s = await c.find({}).limit(2).toArray();
console.log(JSON.stringify(s.map((d) => Object.fromEntries(Object.entries(d).map(([k, v]) => [k, k.match(/pass|otp|token|hash/i) ? '<redacted>' : v]))), null, 1).slice(0, 2500));
console.log('indexes:', JSON.stringify(await c.indexes()));
const ids = (await c.find({}, { projection: { _id: 1 } }).toArray()).map((d) => d._id);
const overlap = await db.collection('contact').countDocuments({ _id: { $in: ids } });
console.log('customers _ids that also exist in contact:', overlap);
await mongoose.disconnect();
